version: '3'
services:
  base:
    build: .
    image: ${COMPOSE_PROJECT_NAME}_base

  cmd: &cmd
    image: ${COMPOSE_PROJECT_NAME}_base
    volumes:
      - ./confs/${CONF_NAME}:/etc/openvpn

  openvpn:
    <<: *cmd
    cap_add:
     - NET_ADMIN
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always

  genconf:
  # Use it with "docker-compose run genconf"
  # Make sure that you have properly filled with data .env file
    <<: *cmd
    command: ovpn_genconfig -u ${SERVER_NAME}

  initpki:
  # Use it with "docker-compose run genconf"
  # Make sure that you have properly filled with data .env file
    <<: *cmd
    command: ovpn_initpki

  client:
    <<: *cmd
    command: easyrsa build-client-full ${CLIENT_NAME}

  client_nopass:
    <<: *cmd
    command: easyrsa build-client-full ${CLIENT_NAME} nopass

  getclient:
    <<: *cmd
    command: ovpn_getclient ${CLIENT_NAME} combined >> /etc/openvpn/clients/${CLIENT_NAME}.ovpn

  getclient_all:
  # Use this to get all confs for clients
    <<: *cmd
    command: ovpn_getclient_all

  copykeys:
    <<: *cmd
    command: ovpn_copy_server_files