version: '3'
services:
#  openvpn:
#    cap_add:
#     - NET_ADMIN
#    build:
#      dockerfile: Dockerfile
#    container_name: openvpn
#    ports:
#     - "1194:1194/udp"
#    restart: always
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn

  cmd: &base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./confs/${CONF_NAME}:/etc/openvpn

  genconf:
  # Use it with "docker-compose run genconf"
  # Make sure that you have properly filled with data .env file
    <<: *base
    command: ovpn_genconfig -u ${SERVER_NAME}

  client:
    <<: *base
    command: easyrsa build-client-full CLIENTNAME nopass