version: '3'
services:
#  openvpn:
#    cap_add:
#     - NET_ADMIN
#    build:
#      dockerfile: Dockerfile
#    container_name: openvpn
#    ports:
#     - "1194:1194/udp"
#    restart: always
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn

  rsa: &base
    build:
      context: .
      dockerfile: Dockerfile
    command: ovpn_initpki
    volumes:
      - local_conf:/etc/openvpn

  genconfig:
    <<: *base
    command: ovpn_genconfig -u udp://VPN.SERVERNAME.COM

  client:
    <<: *base
    command: easyrsa build-client-full CLIENTNAME nopass



volumes:
  openvpn: