version: '3'
services:
  cmd: &base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./confs/${CONF_NAME}:/etc/openvpn

  openvpn:
    <<: *base
    cap_add:
     - NET_ADMIN
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always

  genconf:
  # Use it with "docker-compose run genconf"
  # Make sure that you have properly filled with data .env file
    <<: *base
    command: ovpn_genconfig -u ${SERVER_NAME}

  initpki:
  # Use it with "docker-compose run genconf"
  # Make sure that you have properly filled with data .env file
    <<: *base
    command: ovpn_initpki

  client:
    <<: *base
    command: easyrsa build-client-full ${CLIENT_NAME}

  getclient:
    <<: *base
    command: easyrsa build-client-full ${CLIENT_NAME}